aws:
    region: ENC[AES256_GCM,data:JhpwNc04p2jf,iv:Nvr09+nzlyEmpELro9SeUhmmFyUyP7Z014NLIRYEp4g=,tag:IXmMbiI09uPVYRj9LYadDw==,type:str]
    buckets:
        - ENC[AES256_GCM,data:0HuBeijp2cDubRZJUVyEkxXuvil2,iv:BB5hRJgWY4wgX7HX7CySt0YQSBuMJLQvYXIlj6MaO14=,tag:VjcGAQa+EICbTB4q1pjwJA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2025-12-08T17:07:38Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEmenVSHdzj9lKZJ84olAYLAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMKr/vofgOssa//x4GAgEQgDu/wNvkjGwIKOTcNksP1I5PEdDvg9N0+HVeTbmJCTOg16i11L9z7SbDi4Y5btE9qzo68vRwBPPYoSsnWQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-08T17:07:39Z"
    mac: ENC[AES256_GCM,data:DukV7aV4uJpIbDsERNLFuTI0H/4YBdOzi1Jq7HbRDqDvQYAZ39HFJQDj6wN4flvx3uHCc/3bdbuj9hH2FWGj6cE1+0oozYNsvpxLdeWUpDgHSLjmouhrDK4hHwRDrraXOGuiaNENsbjVttdjPvMJAhjUQLPfzued1fH3igHwj7Q=,iv:NQhBHaBnBfU5AV2NlcbjdDmPRZNK6ifBJPxTpjlEgQU=,tag:9TlAtRERpMxaxNQiWv6WlA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
