aws:
    region: ENC[AES256_GCM,data:9EyBUOhjaDEy,iv:6wiySnSq3MX8OHE1jTjy0eIl87WVQxU7tydLt67jQsk=,tag:bfvrPrKpuC1+pTz8mLtnvA==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:K5RaiJpeFcCvKt3meNHo3n6qKUDLET9FbtzyN7EU,iv:C4pqvrMeXZhM2SPWXIy/SZhoaBuKTqcI2rbnNQr26SM=,tag:4xh4WZxiPa6keb71QLaAjA==,type:str]
                    - ENC[AES256_GCM,data:6iTc65OYGJOxZc06iy/N,iv:p0U/yCezH3chg/85msaRkBSyx+lh0J55fwsadizcSaQ=,tag:pCNMfj4Y68UWQ8oPip0iDQ==,type:str]
                    - ENC[AES256_GCM,data:gtagIoKRatd5cKhI5A==,iv:nrpusUA4x8MlS5SR9PiBxEc5av3mt3bZ37tRtUOJh90=,tag:8hwcm6oZxKTtW4Ch0YnZTg==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:a4D5MmtnjHjZvx5O9A==,iv:DHMzv767Lr31AGcgachuEUAKuBWdkB2MhExRKaZ6Nks=,tag:4rQsp3bdYxC8qLFeNZI9Pw==,type:str]
                    - ENC[AES256_GCM,data:rFP8dq9E+7gGKwDKUKE=,iv:FUBq9HCCWeh78dbfvI7voNFdC2SNGWrhjrFR9Ztra+o=,tag:hH6mPF3G3/75BSg+T/SUkQ==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:8hNjZpinw2Kac7+PXwTbUZY5523xyynnibZ7lcb6tNO0DkV8H7cdaUQ+ag==,iv:6GtTbk4vQyrt+vzC3MPaAMDrXpE8jaV/rG4Htf6qRIY=,tag:iEZMR2Bq9FbJs4UEPq9+tw==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:Y3182m802Mh+5Cr51LSTvdc=,iv:kcMuTvGVzaonD40ygNDYizzvaSuxFtqN/DzL+dK+yHE=,tag:YmFVp3WdMm+DGhpzWgIFjA==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:JlKQLBC12qUgMH+LCCLTTOwLBSo3X8U5fcfX/m/MdMNOv3XRT3ZIrg==,iv:6zcxeGWrWzPXBHl9f6KyfUm3TueI8snvYTmpSS1uaHY=,tag:NnY41duUC3RNbPRWJc1Y8g==,type:str]
                - ENC[AES256_GCM,data:GFIDg55J7y1k5dcdzA8h6eylyicxc6QjlybWfDgue5GJBY6I4A9V1A==,iv:nwFNal9pkjKGlL3Z1BarYE4RqHQ2Cn59LoH25fTK8jw=,tag:OQCfPzSpOZ3SZR/DoWH+gg==,type:str]
            roles:
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:hY4QvT5OlhbQneKlguZQbL6DCcHZ,iv:mve2OUCP2IM+AY1dhL9unUakDCAvlj/uQMLgRFUjPsM=,tag:2/5CsBhonhJ9nTrsbnGyqA==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:9fRU0BAlxMdCiXttLxCFNxCiQQry6DY8nQmPDJ/n,iv:ikc3sb+0m29pQbjZdArqkvOxIU3MVfgygs2meZ5LfZU=,tag:4z52mWfw1bPC293x+NJ+gg==,type:str]
                        - ENC[AES256_GCM,data:vNIgVSPCwlQjRceGrJw6,iv:2eOccqeWo1i8oq20kSrv6Q6i5oTCOjXqmnM+HSy7TtU=,tag:RjnxfD0nG0Is9DtcxbfhVA==,type:str]
                        - ENC[AES256_GCM,data:PyL9AjwAfxwS6u+vlg==,iv:3LYP606N3xi8P2+Z5V4r8DA5tSaf/SJ6HLKnDZ9AIv0=,tag:uVzrR0TsfSfWLpYhFGJWkA==,type:str]
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:H0tDHsgjKQn3dzNZeim/R/yhFA==,iv:gcZyUepIKlpepR7GcGJWQm8B4S8McvbStQM+aUO2YUM=,tag:7rz3XMdHnHIBli6nPwySww==,type:str]
    buckets:
        - ENC[AES256_GCM,data:J9mpwNYXkjVqdFbadtHuyeO/Vq6L,iv:0HqnopUaUbzl7h+nTWaiGzwGMHWbWTBqbpYp2nQaaFI=,tag:I86Hp3Ua3wx2RFevaCenZA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2025-12-08T17:07:37Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgECMFJ6iHCDMt2Qc+r+YZoiAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMcGIEbEOWrOl3X8AiAgEQgDuW0lvyHirkAQcNTQFsLFerly3x+Gbe0F2dmg9cG+murN/SkNqOljKB+6OlfJE6Cxc8xA1R1x6tWk1h2A==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-08T17:07:38Z"
    mac: ENC[AES256_GCM,data:ozHcxbkRNRA0K7DwL0E7dgui2WaFltvj2HskOmYuZrjzq6bm/G8GqhIZpKEYyU3++Qo6O8TaBremRAj7VRg9sWVY9FIeqbaUHMAZ/d371z59xt1SwizuoFQyGAViVkdHaeq0fHDzcW0BSaL47mGhxAscsLe0uFY+u6B9FgfA7Fc=,iv:3pUdQ789xrUyFY4QZm0KphSY4xlb9nUw6J9E19gI6gQ=,tag:RpWNksfDx9LCG0YSbmdL6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
