aws:
    region: ENC[AES256_GCM,data:9F4hxVJwueRq,iv:QHeQ+grKe3hp3GPnNiDULqF+ogGFl/xs4S82Qx/7ynU=,tag:xloBsGUMvWu//0XsHyMkQA==,type:str]
    accounts:
        account_0:
            name: ENC[AES256_GCM,data:3fQtSzReEuOxEL2xph+YAoWngxkd,iv:+udNtAUYM4Pys0lp/mgns3G8GEA2/DAovDrZkLO/P98=,tag:eVrcqygN6SKd8kZfzZbMNg==,type:str]
            id: ENC[AES256_GCM,data:inn65uElTspn3hL+,iv:a7bgoWv5edWuvlZNGuot4bv9Vc4HS6MqLTXUMHPZAUU=,tag:yDxv8geeP1njO5orRGz5tA==,type:str]
        account_1:
            name: ENC[AES256_GCM,data:ocGmo41UHxFYSQ==,iv:F+Z1AXFbRZJBpi3qSy92I0gk7viTJbjagYToKl14NZA=,tag:u9JqirndO5WuPGdlTkQLVg==,type:str]
            id: ENC[AES256_GCM,data:YY2/2V9SlYCo2iWR,iv:anXuw6/QlKa5PyAUfsl6soKsERWC6rBvshl0+GMvVaY=,tag:JTbwGq0LscpsKg+oeKjs2A==,type:str]
        account_2:
            name: ENC[AES256_GCM,data:CqN5grajuxw=,iv:H4SaNqms5jjJ5LWVTwz3S8URoWUL6TjF5S8cWB6kFXA=,tag:KDVK/b7N0qAwVS5dgRvrdw==,type:str]
            id: ENC[AES256_GCM,data:q9bF1qn+2toRVWcU,iv:fcRMtbYQki6/NFA2Qj9gJSVi94KX4i3J5WESUWACPp8=,tag:rO4b3FxqwrZcc9KEhkaToQ==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:98SAldQJNcyIeqDQeDjeVX0=,iv:JD4jK6mjGrd8JiBWDE+4BTEKgzhHwPtFuOB9ihkUetk=,tag:Iwjtf+4eMH2590GyYqiOeA==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:izuZKOSOwYsb1vZ9NS+PYo/ga/BC9XYjyYhKond+,iv:PLlroD2aS0aF1DReF/6R35a/ZCOccoVvblH9EQJS1fU=,tag:lrkwBlCTBTcYdnk7gPej2w==,type:str]
                    - ENC[AES256_GCM,data:/Z0TgWvecy4HatvTuKKh,iv:Zr6HbUozNC//6BcfpBHdlU1/9nlapNy7fZPly3edwj0=,tag:0x9JdJwHkFgk4eYCQnA6vg==,type:str]
                    - ENC[AES256_GCM,data:AffGF7v3TzKoOgWofQ==,iv:mPJ6SmaFVHyFXX4WSB3f/pBLUCO+VguD1m1FV2HCi+c=,tag:VH5NuzFMx3nJonUHvSclWg==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:NJPjuKPwaGM+YhCqug==,iv:ucflBnKTNx/3cXsCcwNnKAjxgYBNMcoN0f+64i5yQdg=,tag:c90AYKkIqkNJI8u7c7GBUw==,type:str]
                    - ENC[AES256_GCM,data:aH/Cu/o3grtPkk7TTXc=,iv:FLL1+ricDB1tXcLYlThE2dV2+A44VY5pXi9iXZiPKyg=,tag:ydodmq6wv+u46yFZPV2b+g==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:lFDlBoQqWzficzPXfSsFA2sQx7oAdOvpL/X4P7SupwpEkw==,iv:yODEaIxedRYMqo1lZ4SNuUALciNCmXlb2CQ87AF8miE=,tag:RPgiQ2TzpniU8jsCq+SvZQ==,type:str]
                sso_role_name: ENC[AES256_GCM,data:2FMriL8fiikSvt4xW36c0cz+1UEMFw==,iv:4J+UfL6NQHsxIPwMuKfbVyKOI3sDPhgVbsv6csB+cFY=,tag:8EnjgZJk73Gm9yW2JdsYXw==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:Tb3Z1CvTjGY/N9VODxYVVBIc9g==,iv:A+XP7jzMYPkG1fBNUHPWm6hzXFpb7T9ectuhyqzDuSE=,tag:mD+7yNFpYKt/e4TOe1SNKA==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:0sDfMRXyGoWuSsl9vKNx,iv:LPOqzUv4ZeaMk3ySTnwCxajnZpaapg4LHLhAMCJfLi4=,tag:jPlcypumN59aLhZ8KELekA==,type:str]
            users:
                user_1:
                    name:
                        first: ENC[AES256_GCM,data:ZsvorrXb,iv:BN84wrx3RT7Hs40BKK557H0BmQn17FZrigMGdftTUxw=,tag:1L0hROfUqF71MlfhOCPiWQ==,type:str]
                        last: ENC[AES256_GCM,data:eEp9xhnJ4Dc=,iv:dmvWuBtfNB6+7xQhFGftmORmTNEkiJUX+P+85LohJIg=,tag:zOw7vg57fvLHNCPnH9lOBw==,type:str]
                    email: ENC[AES256_GCM,data:TAmqcaNzl6xImKRqXzPAn1VqMIkPBZWN,iv:aDlNmIp0tB2NJkWcOeHOz7ka28YAkOP4yHR6Cib1B78=,tag:7BdFEOB4LKpNlcCxX0e9OQ==,type:str]
                    cli-config: ENC[AES256_GCM,data:BvcmM2w=,iv:IsWK6iI1LK4uQ//BcTPNyle1nvM2OK6KZukEjLOrm3c=,tag:9my+pdfYznmMlJNI4nJbtw==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:K9xRoYvt0Qk=,iv:NvFebvS4iAoUIDJUB4WDDmx2VZbGuqyDvDcWYo3m2Jg=,tag:zieQKGOxpr55ZCrcIX3DLA==,type:str]
                user_2:
                    name:
                        first: ENC[AES256_GCM,data:9fOr,iv:YSph71JL2i+c6w2/V5qSErIsjuJS2RLu6CperNvGLD8=,tag:C1j6e4hJOe5tl1B30x0kzQ==,type:str]
                        last: ENC[AES256_GCM,data:XN/0+v2d2A==,iv:OsFpzDbEricvg8DbiXQV37T7EeM8Qn7Jk/dBikdEppc=,tag:qkxAEo6Au99v2XreTbOqrg==,type:str]
                    email: ENC[AES256_GCM,data:H2wETYQSkaNus+WRpP/0t6PaY2q1PzQ=,iv:9NWGY0yg9H+lyjuOW+4DCpHS704Tfmp5VS70MbbeQAo=,tag:bP1pYXMRa1k8CzBJuD+gjA==,type:str]
                    cli-config: ENC[AES256_GCM,data:whqU1f8=,iv:5Il8IEsSdiDGJ4RlHOsICifIL9/5FokxjRU2FwTBzPE=,tag:1H5d8svczN1qWTbYGDvKrQ==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:yYO3YnNoJUICdA==,iv:j5iIxVco2EBZS9TquXjtGiJa7szxS/D129iXURi4Gq0=,tag:GzpEndvNWTEgbqtKvQHMYQ==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:PRZxX9PxXumXJs64aeXpm5nLA8xQ,iv:szTGdFWBjTlSa1x3SFEAszFC0n+akBoTxYiCi1d8e+w=,tag:f679pkPdwFWE7nRFzpe6Kg==,type:str]
                            - ENC[AES256_GCM,data:MFNt860GDgZn5Q==,iv:despmglGs/5WCMinX+BRHl00WS7/lWKtoHanvSIO2sE=,tag:tfEQlvdqwm8KHrw3E0uqJw==,type:str]
                            - ENC[AES256_GCM,data:0tSIz8EMJ+w=,iv:QPloT6+MiVRiHErixSWW4L730OktBv7tVnIM85VK93g=,tag:f6v1+VQC35c2kohtlDR+ag==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:QqPRZ0RPYDo/sxPhR8O4NNaTyVTOPjkDjYFyXRuiLO/56gCOfobT1l0cpA==,iv:PSVcspOBxhHAb/ebsoRL3FJKz/TJfrkMQgofwSljyjs=,tag:BPGIpz/VWUl23K4B47c+AA==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:4QS8hMAP3sevJHulSdfiKIc=,iv:+xJPTSrVyUVnKmElIg3x4zsjxOb4LnP7lW+SaSgqZRo=,tag:swaaBpzErl42xwTBmrC9wg==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:4XtWhKvzh68ODc5FbxHjF81vJFVllmmwzChIFsjTqbSIk/ZqZDscAw==,iv:R3yHgojmIO8AKXD2SkOlyhdDBMD1Ne3YVXbRr+0NWPU=,tag:fVwgEVERZ7BXkEiDZoN7dw==,type:str]
                - ENC[AES256_GCM,data:AQoT5tJjovKp4dXUH3Tfyph63eUXfkNknNmzG/zCmU3kprTlU5GB/w==,iv:qFKw+SfYlLYxITIaokj1C4TmJcXf0ViN5mOAhbsbMtE=,tag:Ow9VD5NGI7DZy+s64SRFWg==,type:str]
            roles:
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:F5R0YxoK5LHFYYoF8phCsO3EfWaY,iv:tAdtd8u5B6dXrv6QsRz+CH9/bduz1ihT2/gV5uNhJaw=,tag:Q1pGXuBNGx4jeejNjbg56A==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:EwT96xMBCkgVsQRdZUQABqHl77eFfSlq0qJSPv+W,iv:Cc/S+JKyqK24GCguCPjiPoY2lzu8rv2fzjHdYldkA9w=,tag:OOWFJlMqu3Dkp7P7pe9HKg==,type:str]
                        - ENC[AES256_GCM,data:hwE3+jM1bcu0rKoS39FU,iv:jYC0aZBWsOrrl7KAeF3xUe+kxcvEtMA5GWCYIXwt8R4=,tag:IANUjXjtdaI0GXaDfs0R0Q==,type:str]
                        - ENC[AES256_GCM,data:m8aGRmgJ2SaxrkyKmQ==,iv:qpnnqsat7mGRaTS4Simt/hJc0nkLLh414d4Z6aWdblE=,tag:YbrFBWVbB/DChfO3Mqp0Vw==,type:str]
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:tiLm/Y5IcqvaMMAuzyU4DVPP,iv:4bkitgwwPY6/XoTTbi6Iq8q1ilbeFhTInTh5qwcHxtY=,tag:SR9sLTKz08Zouju2YiSKwA==,type:str]
                        - ENC[AES256_GCM,data:G1nwAKeL2wtTo16b59GehyJ5Ww==,iv:kMYXYXSwYoIf0PIfjNrFbujauFQ2iUh+lY1k2ic8/oo=,tag:glF3h7XP79Shmay/9tQBbg==,type:str]
                        - ENC[AES256_GCM,data:Wq4vju/5zSdPmz4zEiIOsujEd3a/9A==,iv:NrAcJLxkJzY9wGU03WGPZYMqQ2eLLWHgf9AprGG0Lyg=,tag:GW5Q4oUJNDxaNHAUyEqIYQ==,type:str]
                        - ENC[AES256_GCM,data:riZnBVHcRoR+XQ3rrRM2ZDShzxMhAPg=,iv:z9dSepFLnp0sDF9xBVkK3bhsYSWTCLviCzQ/Dmy8anY=,tag:kTS39d8iN2PZ5HxOYKLVIQ==,type:str]
                        - ENC[AES256_GCM,data:aCXrPQiiu9wXJWDAOM0GxbUG8ZZL,iv:pPMl9JtQSRc9dG+w52GWUDAZzRWjxJ0BucuYxHWZdTw=,tag:0QyJIrnRp5p804MGNcyoJQ==,type:str]
    buckets:
        - ENC[AES256_GCM,data:cPsLypRWOjqVAWWH4nhcW37r,iv:RIdebbsWay6a2HtfdH+dCzjzKskEB/1iMR79wwy4K7s=,tag:Ltujd3Qy57qlAcaXNgHTNw==,type:str]
        - ENC[AES256_GCM,data:B/8jXdZClykZylYE8EdiG9Y=,iv:9W4k9d2MqHEuYu/6kYYM1g9jRZkeoictBHa+OZVMaSU=,tag:ale6hgFStu3edxOBR0leWA==,type:str]
        - ENC[AES256_GCM,data:WuHuMCCunGKIkdSuLuGMlzs70MB9kU600w==,iv:dkQfQU3Sf9wzkOnH2rkZmppGNu7JrUa6gNU8L9VjOLs=,tag:fdZWySnU6QYhkaLWGI9OXg==,type:str]
        - ENC[AES256_GCM,data:XpJSnKCkSrRARM9m6fKUbL++O1r0O6TFPRKlOxs=,iv:lgQnfRu0NTknA+ShV9GfkL54otVKqYEiNLG0hZ04jpk=,tag:qyHRtkVGJTO//iOMBEvrpg==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:Dias1DYfUOtf+Uzr+Q==,iv:A+yB5ddvTvyOTAGYAVsABDWyrFz6HpK9beowGW2WwSc=,tag:zNaLunzMOXWl8aNcyIVsjg==,type:str]
          description: ENC[AES256_GCM,data:FR9n/1LRfWR3O0rZGg==,iv:odosDGuu6kuB7mnN0aPj1QFvUWYZ3EDWh/omlkx/ZSA=,tag:hvfpGwdaskKxKFh7/vhxpg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:xvTA6dpRFrWuvgTcCZpe,iv:G4DiaxqkhjHmouja1VfD1QNsHgVeBzvr2jQU0UHz+3A=,tag:trlHJltmoQB6RWLf5E2xBA==,type:str]
          extra_policy:
            - id: ENC[AES256_GCM,data:+nX9NqZQc/Gyg1MgGHxl75u/DVTuY5w2B+hIyQ8FZmyGhe8=,iv:NNvGhgdZobTSXES0xq5owWm7/Zk51dfasRVCko6UPyQ=,tag:/kIOyBsaPoi3yezk/zvATQ==,type:str]
              principals:
                type: ENC[AES256_GCM,data:Lc7i,iv:NFaPjxSLuxpnEbCR9Kcw5oTCDAoyDEslMqQhb8zYMWc=,tag:AQ8LedW0GZhhMdVnWFmGCg==,type:str]
                identifiers:
                    - ENC[AES256_GCM,data:6+GRXmDPPeM5teVQW3ymJ1PeS6ZbFYbJgCJHupQt5G2nTin6srzXy8D0jpCZ,iv:0tofhIg5ISW8yX7PL0eseh6Z97344izXiSGMxwdaqZo=,tag:Ex2Wiq6Q1E8ZuZ780Ip/yA==,type:str]
                    - ENC[AES256_GCM,data:690G5OlaMfjdTWfLMkGY9S+S/DCNeq8sG1u++ZxadN8TRtl4YDnH7PpRCcyNd5qw4jpE,iv:C6u+NxIqC3qstS12YdrFh7JNCoFFEcyl5Mj7gGy1lWo=,tag:2C081i5zFNj7gWOZifsWfA==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:zx3A0HZjIQ0vSeE=,iv:JoAHcfTK16q167Cmkdsf46J3C76OOeDMFuzoFxN+zbE=,tag:UeHFwWnoTMvyR1kmgi747Q==,type:str]
          limit: ENC[AES256_GCM,data:p8x5Nu+3Uqk=,iv:32tsibStH2m9VJE0dLBRzA14fXkswNh2Nb9Q6dnv/6I=,tag:vgdv0rZaVXPFvflikbBaoQ==,type:str]
          notify: ENC[AES256_GCM,data:Vtz5A1R0qYD+lBPoAiWJ1qmcBYtzIn77,iv:t0lO561+OHzEmoFNbmKHtUb3meTYfoYqvC6P4wu38YA=,tag:ZKK/Vg4AvrHh/+3cEkQvyQ==,type:str]
sops:
    kms:
        - arn: ${KMS_KEY}
          created_at: "2026-02-01T18:33:53Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgFkukeKFYf9eQ8oaSYGBd7pAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMED+nm2OWJuu++SeXAgEQgDu1KMr2TU/S7ODcHnbPcHMpNc74xzo/rvzroZxQzFcIz6pGlqbxdB1m/LmHOjNPrdopjeqMoN9SGHXJqQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-01T18:33:54Z"
    mac: ENC[AES256_GCM,data:Qe9e04W/NYabtoNqqSV0r1jy7NSV33NjaLX9Buc83KfOC6syrTj93c4w8p8XVWsm1JSEtutbo52Cf/YAPNkHSML7U62FYa5y9hxuL3imysQ4O6O/NDDIpJ1lghbwh9goAn0wcj1svDOmIrrn/VU5z6sK27s/v0II0EZRMlGVPaU=,iv:mp3V0aqsc3T6nhiIWbamzj18hpZMwEfXfxm39WQzmyY=,tag:auM9x0KCsV2+k6RI+Ep5bw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
