aws:
    region: ENC[AES256_GCM,data:q95UCdFuX+kJ,iv:kRPowwrUPhj21j9Y2DM8IcLETg7AuAUeXxVuo4/UHeI=,tag:04zL9IekN41FJUoO4RoysA==,type:str]
    accounts:
        account_0:
            name: ENC[AES256_GCM,data:8JK4AhNPwiDayWnvW65OrKW7iOfl,iv:KZxSg/IlNed2cflLGmS965Mb3oApFilGxOgBjwCqqXY=,tag:nWUQdeg/LKtudRDOZRhT7w==,type:str]
            id: ENC[AES256_GCM,data:N+50vtxgw2WK4XoA,iv:MGNuvjyt65Ma5+E1x6ej4j7Q6g71ZWegG8VlbFjVFJU=,tag:nwcEuntzLRGWKgTSsHhY6g==,type:str]
        account_1:
            name: ENC[AES256_GCM,data:rj5Z622g+buslA==,iv:yvzsycqBvodge3MhokJYeRfebzMAXu2iDfE9arId2E8=,tag:K+CnraOYMdDWcFRQV21myw==,type:str]
            id: ENC[AES256_GCM,data:dXig4gYQHZbeXSi9,iv:Abva4SjEaGphwTk2vQDBclegHroHcnXLNoCyRSVXk44=,tag:5/tZFsWJryvrcYynC1BoIA==,type:str]
        account_2:
            name: ENC[AES256_GCM,data:2DZ8XKJWeBg=,iv:SCAqfQ2krbC/5V0OnwML7xzYj84bzP8nJWIJzK8ab9Y=,tag:5EX6FxG+j02Ed5rvrVYCaQ==,type:str]
            id: ENC[AES256_GCM,data:AFoeLxBQDqqlnrEh,iv:ZIefwSHcrXD2Co4O03C2kTDMUGuJpwStRI5gmPp+5MU=,tag:pJgPS8lYcqPXgEk5V1T4VA==,type:str]
    aws_service_access_principals:
        - ENC[AES256_GCM,data:/gItCZ9CtWCvnr+PZbekeP8=,iv:ddS0xFi2cWBrHXbzFfppb+YqYtgQMJD6veNEOKVLYaU=,tag:3zhV6F6C6mE+lpgpKFhfqA==,type:str]
    iam:
        roles:
            provisioner:
                policies:
                    - ENC[AES256_GCM,data:dSr46sKO09lvBFLi34+F4E8btBaEikTiyVtEiM1h,iv:9EUeNvz2fH3kpns4bFmNEB35Oxva3kdLV66xLv396uE=,tag:oOz9TJ3etIYrYb3IXdcsVg==,type:str]
                    - ENC[AES256_GCM,data:kpC6ll0ParqGUc7diI47,iv:P5O9u7P+662/fK4b1WDsGC/dUM9xxoVPhVxtwOYG73c=,tag:tX6Jw+SmhJBbLpBdGVmnSQ==,type:str]
                    - ENC[AES256_GCM,data:17wQLoiAJUjPS8tlmg==,iv:EzIOTjhMaDx88LxQjjmyZi9q1xPD0ZYsLPGXAhxy4Xc=,tag:IK1h+ht13h2N7Q+bh5GYpQ==,type:str]
                allowed:
                    - ENC[AES256_GCM,data:edbt9oZNeBTMyo3Amw==,iv:AUMonbxZLE8+KnKrCq/qYrpPwCqd1+AlTxEEQra8DUk=,tag:ZRFrji0iA85PDYiJbFZsYg==,type:str]
                    - ENC[AES256_GCM,data:odKj4ghcKvhRzMacbc8=,iv:dbt6sOiQpryUr+4hyAl3UHX2IxO9DPBqmN/qG7zzIZg=,tag:4X9j8qL0RRhvBQ6bx5nrSg==,type:str]
        sso:
            config:
                sso_start_url: ENC[AES256_GCM,data:H+tuAVlHDaTG9urRAIC7Iv3ukLTMePN+MCf8SQ2UWcf67g==,iv:Md8diwa0UkAemqx2ItHh12QH6Zi5lNpajh6IrbxrejE=,tag:95pSywx7wwUBlBo8u5R13Q==,type:str]
                sso_role_name: ENC[AES256_GCM,data:xmBOtAcT/7kfXTjxH8o6vK2sM+NGkA==,iv:zVr7d0ilYclsNT8T00/9xnKXV2eiMlTcu/kRaFknDT4=,tag:Bvgpn1ap9GMhq42ZRqb/RQ==,type:str]
            managed_policies_map:
                Administrator:
                    - ENC[AES256_GCM,data:1pvTtLSWP9QWR5HLNvju5tJ77g==,iv:AOF9IMupWhPSXNrqv3bAIMQZUbptYHNmi4Vo+EroGM4=,tag:vUnmgjjrwSfFefFNA37BPw==,type:str]
                Developer:
                    - ENC[AES256_GCM,data:PTUDRXyEAne8K6oJ4Zwv,iv:4KUZRohIBXaVg5SkI2eE5EV6nDnbZLd8aAo1XoKmtG4=,tag:ZfUqq1Y2gJhTs5kO3zN4Tg==,type:str]
            users:
                user_1:
                    name:
                        first: ENC[AES256_GCM,data:O69NXC/H,iv:MDhu+U/REFLzE9erVcu2M6C+RMBmCYuVq+cpIQ1EGrI=,tag:B3EpSaDzYX6cBlZer3iEQQ==,type:str]
                        last: ENC[AES256_GCM,data:fjITrZnAJ9k=,iv:4YBkuv87j390/kZRoTCnzAhiHaAMRl2mr3OV8FFlwVA=,tag:JI06OQu1+RyQeByKLE/xVQ==,type:str]
                    email: ENC[AES256_GCM,data:DIwUgL1GjFgk4Kn9wdk8n/WjscVARWPg,iv:+vKHYuudN9mov8xn41C0v0L8eh/JE5OVarmlH2k5S1M=,tag:nP8xoxI6YQfTjTNr9SBUwg==,type:str]
                    cli-config: ENC[AES256_GCM,data:zErmbfI=,iv:qGoORu7urqlZANT1Ez/fM/d5hGpkxiFSkWLTzpB1kG4=,tag:6P+2sA+dl59udI6XxbTI+w==,type:bool]
                    groups:
                        - ENC[AES256_GCM,data:gkTOYyUh8wI=,iv:n1UeHAWY4g21DQUa1qPr+zmscj9ahOAxrW5HV6JOvbE=,tag:9d9spx7AjwG4GnQsgsffqQ==,type:str]
                user_2:
                    name:
                        first: ENC[AES256_GCM,data:urpJ,iv:5EQYICYc4S3cm19xBYHpMjwStRhsONoh58eTrb8Q0gc=,tag:HnzDy5/Fi49XqPF5iNwFjw==,type:str]
                        last: ENC[AES256_GCM,data:Zw3h0/3zbw==,iv:LQrImnB3CoyokHRqFbg8BuiZEnnhJ8/L2qTL0BMV7Ww=,tag:6YTf14V0mgZl1hZmjHxi3g==,type:str]
                    email: ENC[AES256_GCM,data:kyl/f7Ig6fvNB83qvRcyMWy3er70zo8=,iv:6nSct4N8Rfbi2MlXl3+KaIC1WTd2wlPcezGpYT+iTZo=,tag:y+3blE+YwJdIm0L5PG0aPg==,type:str]
                    cli-config: ENC[AES256_GCM,data:xzP3ifk=,iv:rul/mrmxNooFFj1NYDEfw7prXHaZ7sflCpSwzztN9HY=,tag:92s0d5/CpMfSXPo0vl/itA==,type:bool]
                    permissions:
                        Developer:
                            accounts:
                                - ENC[AES256_GCM,data:u23ViYC0ohIq+Q==,iv:GEMvNs9HLcXxSnHtD2GYgZK2NrJaY3AkEyF3XEvdZnA=,tag:atJlPBiVSXWu5j/V60v3cA==,type:str]
            groups:
                Founders:
                    Administrator:
                        accounts:
                            - ENC[AES256_GCM,data:J1JzofrT7VuNGfjicjkMfE6NNiH/,iv:t5w2dsFyfc84VcFUGlRRz0Hf9JV0X4TMzFESkHkeZDM=,tag:3c3/yk77V4Jv/LUDULUVgg==,type:str]
                            - ENC[AES256_GCM,data:RG+TzojSVA97VQ==,iv:4u7DD3/hX4ib7oyXKVyXJo4vtByYP4vOlQOA5po9ZIg=,tag:b5gTib9PkTh0hMJniGudaA==,type:str]
                            - ENC[AES256_GCM,data:xQ3CftHUZxw=,iv:0WOeXFOIUU3feBQ9WtRUyJkAZYjUyxwYLMyQdSOgM2I=,tag:9yfyzlSAeQdCtjrJ7Ihahg==,type:str]
        oidc:
            url: ENC[AES256_GCM,data:6QFBsBHResH3iNYilB5E+vwmEoVOmg9C8Q++bnkNnaRzmBlqSRFj26Vt/Q==,iv:P73GFyYeUQKxL62Xa41WDX2DPYKzHJfpOxkLVhMzapA=,tag:4Hz7ASGYKTae548SMF4FKQ==,type:str]
            client_id_list:
                - ENC[AES256_GCM,data:pbIorxJAuUd5VDwuEZrnTRo=,iv:gxJK7F0AEFfLUAJgQ0dnxMsyV58xli8hx/b7PwN+G6I=,tag:KC3Y0wsy7SUcevs9TZUhWg==,type:str]
            thumbprint_list:
                - ENC[AES256_GCM,data:+WQgkUr63iq0E3gq/8/dsyz/4xA2mQphEcmYF2K/ldEHnwxb7PUvOg==,iv:toD60w2TkBJXQI1Q0H6yIjug7VUfZbWXibDjRd4QCqE=,tag:QqMBLU/P65ErcBUiFhI1tQ==,type:str]
                - ENC[AES256_GCM,data:bF6oQJS2LNbvR8H1+5LZXvfJyZRGOi8jXzzO6YZnzefqDDkPat5OAQ==,iv:dX69u3bBhTpECB9PJPhIZNAe9YzTNoruTjMZ8SWVrTk=,tag:PpFCUpTQDCy5JqL7Fz795w==,type:str]
            roles:
                power_github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:nTaiEGlwIwiO7UJ/MvKn9XvxpQtj,iv:/DlYxgUy2NmlhJBQAPODoiBDFu2/HQLBmpxjPl8234U=,tag:Dxn1TCUB0EIZnmkAZCNugQ==,type:str]
                    policies:
                        - ENC[AES256_GCM,data:7qrw0H/Rguy5LhaiP9oNBESU/gD6/TzMwcSPyebQ,iv:c8loIIDku5XcxY+Aa2pqadsAOTx3HyNeRuMqTk5c7yU=,tag:tyQTEuZsT+UbUM6xcdGK3g==,type:str]
                        - ENC[AES256_GCM,data:42YViGJ0qdDcWw7mJuXm,iv:/ApYNS+sEIfjVYjxHT17oP7PlO9SxKzjvdi807WYUKY=,tag:BUknxWZf0qTcvSTByogNWg==,type:str]
                        - ENC[AES256_GCM,data:V14901tQNP1hRKiWMw==,iv:W2E6OvVCFNcSRDQX/43W0ePX5PVy2LufE0vt+/lcJN0=,tag:NSWkBtx30eAZxFBWKa5Fug==,type:str]
                github_actions:
                    repositories:
                        - ENC[AES256_GCM,data:TgFMQyvKApmDxeQJ6UfomrfD,iv:Ca5RwHcKPlnZdDrYyEJiwcY0uYkC24EZlBi/bnoMAVc=,tag:SG+bc4ZpP1CN1Ahk+cmQTA==,type:str]
                        - ENC[AES256_GCM,data:+RGKuh2yNfxpTkE6a5S4hruwTw==,iv:qlUsjshvrOCgojYAh4jWtHz+o2IALhgDtYISx/gxxRw=,tag:eyGdxaz/AGly6PITtgaQyg==,type:str]
                        - ENC[AES256_GCM,data:P81m+rf0/mfCEHQNftUt1MbKWFHAFQ==,iv:IyiqWbYmv4ehDtuF9UXb6JNlikZ4aCEgE28QuvJhXV0=,tag:8bbr4XfDDeYzkR5d9pwhgw==,type:str]
                        - ENC[AES256_GCM,data:DXtDbbpVE5dMHIn/8a/VFSw7ZJJqXmo=,iv:L2TerBpSHCyTbfHVZ0zPd6bUp01ER4xM9tAD/WViX0A=,tag:5gL8tM7A5BJnOiDpeLZ1mQ==,type:str]
    buckets:
        - ENC[AES256_GCM,data:aM0l1li0dtZD4bo0EDtp9uQ=,iv:Y36MnvL87vhNvZzzXdw8g0eX1ZX0QXkmIFaqBAA+Elo=,tag:TvY/KXx6ZYCoQpp/ZkfnYA==,type:str]
        - ENC[AES256_GCM,data:cNCPgquGBvdCat3k2Bx6mmt9Cy0=,iv:21QXwYOs6vHqjDd3MPOK9RMX8rpcJAlpuSLKxS1Ir0g=,tag:ghYPbAEyOXkK9Z7rEQII/Q==,type:str]
        - ENC[AES256_GCM,data:sJrUeaFHJAGSAO9irtf7ZYvf,iv:pxILu6UYMsatuvY1+Wh2J7QarqKzR8joWzbyvVbEIxM=,tag:mTugP/Lk9DpvVq3Gmpb+bQ==,type:str]
        - ENC[AES256_GCM,data:/FwrATJFWNsV30oRrw3sF0M=,iv:g39ejNCj3WNDC6eCXoBfG0UMckF/2ili49TLXi6T/as=,tag:5kVGUsIiTeX5bjCa53CImw==,type:str]
        - ENC[AES256_GCM,data:a+IH/421QpEZ3bJfCVEkklW5Ocjp,iv:lvGot/jCoOAhQoy4cQ0lw0V/SooqF+YnjCObESJxZWA=,tag:X9yQsxiJu3kMtSJnQzd7iw==,type:str]
        - ENC[AES256_GCM,data:r8rD120hHGrmbyIRVRE2IXLvJ/Nuz3PfnQ==,iv:RTDKvsC9yd0IBaBMt+fQz49mT+AV5BPBNTNwt8HJBPE=,tag:SLnXexbo+SGyB/XXPNbI2A==,type:str]
        - ENC[AES256_GCM,data:0om/AnjTLD9JyPV/62aGvPV9nHb0eY8d3dyNdcQ=,iv:+gvJJ0eYaBISSl/l09IRcnRakTxvl9GNFcwNYxjuNuk=,tag:NIyr7MsCn+rqSoPdC/2FIw==,type:str]
    kms-keys:
        - name: ENC[AES256_GCM,data:5YEVbftl57QNV1Hyjg==,iv:3wMn/7O3z/6rjp0+1YqX/NKaLnQeudWt4NPBMjX1mAU=,tag:nkAlo3zGM180hqZuOrXoFA==,type:str]
          description: ENC[AES256_GCM,data:nWQae7x5wJuGIvXzvg==,iv:xaaaq/KmiBfYDa9skU1vqB2DTt6vYDQhz2R5evRmGS8=,tag:Z7ZpR4VmJp3pxfETndh+yg==,type:str]
          deletion_window: null
          key_usage: ENC[AES256_GCM,data:uhAFSYqDFsiuOKeGpx5R,iv:m2XDNMYgLcWHUXXqgiUt+emhsPP0XaDpAzmWPtHEcXE=,tag:c2+yiTy1buP5wmWTwFSf+g==,type:str]
          extra_policy:
            - id: ENC[AES256_GCM,data:63cIpAdJZCK7EFoi1JT0tZ8c7ePH/ehZxwGGKYTM5UjxHMg=,iv:OwvYbCTqGBfb8cgeC7/NVO5KFQd0eURV1z0oljRYe1U=,tag:ygxCUaux4E9Mx7FQ4WlKfA==,type:str]
              principals:
                type: ENC[AES256_GCM,data:+XL5,iv:bQZ4q73magN2vQ1127dymk+1GPFw3NPhriWFWO3Nx8E=,tag:137NyMjfGVzpYVPFRLAVGw==,type:str]
                identifiers:
                    - ENC[AES256_GCM,data:11ECxgubpjw/obMAMlGWPg/olYQFcTIoYRZk+Nw4UWwgdF40BvaNkwkaRAj0,iv:tDwXkwSCtTHsaBNfL88XPLuiiTGWVb+K5lQAtlWGcng=,tag:+ndy+vvcdkJqDF6rzVPuXQ==,type:str]
                    - ENC[AES256_GCM,data:VMYOkwY12GH4hPFtomkwJeZ0wPtlUKZ+Z4lWwI+zABCTlXbgUT5mXQ8o1sO1Y66xs5WQ,iv:WkcWYLQiz953RfVdW9OKJpBx7rh0tR3uBKe39F9/Psg=,tag:Gk1wYXdGRATR1grkyuNePg==,type:str]
    budgets:
        - name: ENC[AES256_GCM,data:WbRRpk/F7qE3IBU=,iv:rDsEJQ2XG8K+eEIgs3MGs+nPkjl2bNVzEv7120qBr9s=,tag:clLQYKNXH7mw0EKqHqLaXA==,type:str]
          limit: ENC[AES256_GCM,data:LlxcYgjYDoM=,iv:jBktrYQWvsm8lTnVVBXL6ValyHtsPi3/xXkv4t3LZhs=,tag:8bYt3LAYtm8uycrj5wrbnA==,type:str]
          notify: ENC[AES256_GCM,data:slw8KY3p37UzVaA98bZEoBQPNoqLfksi,iv:PgFipCiPSJ0FAV1NNn4z6olPsIxS8ougA+F+z9ZKzSw=,tag:tTWGsGUmr1qGZ5CqCfV2+A==,type:str]
sops:
    kms:
        - arn: ${KMS_KEY}
          created_at: "2026-02-01T18:11:53Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgENRYIyrYTNz3pdUHflTYWmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM5t61ZcCBDMt4LHy+AgEQgDspVqQg+4nviVk84UYO+sh8GCabQ9mb9XVJMO1hMJQjVl9dTMd6ML0oytn+djpNGwmHlYh9bODTfWOjSA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-02-01T18:11:54Z"
    mac: ENC[AES256_GCM,data:1ibOeY0zvDn1XzDwPtjZOi2zzL0dM5Y1U3x1VNTZVnYZLvI3jgFVQBW9IRrbeBE9ljgNaholFmBknVCG2oWSnsswPxSPwHyhJ82hR1P9HG6oFdjFKvnEwT+oMmVJJzmpq63doo4gUr7ZZj8EFEk+vhPeJBswfgB4Rz9O+B1JyyU=,iv:vzBnoTTjec8o4hA6P+iQfUTlgYt1XmfSFOF/SAH0OHk=,tag:vZuNNiRGsuDOvnBSZxcCMQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
