aws: {}
sops:
    kms:
        - arn: arn:aws:kms:eu-west-3:877759700856:key/b3ac1035-b1f6-424a-bfe9-a6ec592e7487
          created_at: "2025-12-08T17:07:39Z"
          enc: AQICAHiFgQKnfZQbS0qksdcKnEcqfA3yd0cfbwGnH+L5HeKvdgEDNpEsZVmAN0QR8p5IzWJSAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMv0a+Azl8qZRbeDQWAgEQgDvF5kzRCrBp8pIi0kF2KlJ7+Uk/YP89obxSycnHXTy+Ct6uIPzfkQpauEKS8SJ67Y0YP1Hbo4yjYId0xA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-12-08T17:07:40Z"
    mac: ENC[AES256_GCM,data:3fPzhQHlKwushpbWDl5Jl/7fm3R541LzlI110Zj9/DoiJHVUFVhWLkguvXhD8zY9gctuFT/c/8Z2RPDVvIsf2oDzRPCo7r96/Geo5IPomfa8javSsl0KiHgFjDAZoX9gArg5oECisMJ9wbrpL8YzqvxJwHZw9cH4GKLmi5tO81c=,iv:IQGkNwhzD10oaJMVzVaqkj6bCkocJJ7a2r2KrBveBPE=,tag:wQ0FAjfU+WK653JGqkiEzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
